version: 2.1

orbs:
    node: circleci/node@3.0.0
    aws-cli: circleci/aws-cli@1.0
    aws-ecr: circleci/aws-ecr@6.12.2
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:   
    install-and-test:
        docker:
            - image: circleci/node:12-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package-lock.json" }}
                - v1-dependencies-
            - run:
                name: install from npm
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules
            - run: 
                name: Testing
                command: npm run test -- --no-watch --no-progress --browsers=Firefox               
workflows:
    build-and-deploy:
        jobs:  
            - install-and-test
            - aws-ecr/build-and-push-image:
                    aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
                    aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
                    aws-region: "${AWS_DEFAULT_REGION}"
                    profile-name: "CircleCI"
                    repo: "angular-test"
                    tag: "latest"
                    requires:
                        - install-and-test
            - aws-ecs/deploy-service-update:
                    requires:
                        - aws-ecr/build-and-push-image
                    family: "angular-test"
                    cluster-name: "${AWS_CLUSTER_NAME}"
                    container-image-name-updates: "container=angular-test,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/angular-test:latest"
                    verify-revision-is-deployed: true